name: Fetch Quote
on:
  schedule: # Run workflow automatically
    - cron: "0 0 * * *" 
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest quotes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update contrib graph
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: nmahesh20
          outputs: |
            Assets/github-contribution-grid-snake-light.gif?palette=github-light
            Assets/github-contribution-grid-snake-dark.gif?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: main        # Tells the action to target your main branch
          build_dir: Assets
          keep_history: true         
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Quotes
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://www.quotationspage.com/data/mqotd.rss"
          max_post_count: 4
          disable_html_encoding: true
          template: $newline $counter.  $description <br> &emsp;&emsp;&emsp; <i>-by $title</i> $newline
